---
version: 1.2.0
slug: rhasspy-speech
name: rhasspy-speech
description: Speech-to-text system from Rhasspy
url: https://github.com/rhasspy/hassio-addons/tree/master/rhasspy-speech
arch:
  - amd64
  - aarch64
init: false
discovery:
  - wyoming
map:
  - share:rw
ingress: true
homeassistant_api: true
options:
  debug_logging: false
schema:
  debug_logging: bool
ports:
  "10300/tcp": null
homeassistant: 2023.11.0
