---
version: 1.4.8
slug: rhasspy-speech
name: rhasspy-speech
description: Speech-to-text system from Rhasspy
url: https://github.com/rhasspy/hassio-addons/tree/master/rhasspy-speech
arch:
  - amd64
  - aarch64
init: false
discovery:
  - wyoming
map:
  - share:rw
ingress: true
homeassistant_api: true
options:
  # Audio
  volume_multiplier: 1.0
  # VAD
  vad: true
  vad_threshold: 0.5
  before_speech_seconds: 0.7
  # Speex
  speex: false
  speex_noise_suppression: -30
  speex_auto_gain: 4000
  # Edit distance
  norm_distance_threshold: 0.2
  # Transcribers
  max_active: 7000
  lattice_beam: 8.0
  acoustic_scale: 1.0
  beam: 24.0
  nbest: 5
  #
  streaming: true
  decode_mode: "arpa"
  arpa_rescore_order: 5
  # Misc
  debug_logging: false
schema:
  # Audio
  volume_multiplier: float
  # VAD
  vad: bool
  vad_threshold: float
  before_speech_seconds: float
  # Speex
  speex: bool
  speex_noise_suppression: int
  speex_auto_gain: int
  # Edit distance
  norm_distance_threshold: float
  # Transcribers
  max_active: int
  lattice_beam: float
  acoustic_scale: float
  beam: float
  nbest: int
  #
  streaming: bool
  decode_mode: |
    list(grammar|arpa|arpa_rescore)
  arpa_rescore_order: int
  # Misc
  debug_logging: bool
ports:
  "10300/tcp": null
homeassistant: 2023.11.0
